FROM openjdk:8-jre-alpine
# copy application WAR (with libraries inside)
COPY ./Documents/drop_dilitrust/file_hanlder/target/file_hanlder-0.0.1-SNAPSHOT.jar /file_hanlder.jar
COPY Documents/drop_dilitrust/file_hanlder/target/config.yml /config.yml
RUN mkdir uploaded
# specify default command
CMD ["/usr/bin/java", "-jar", "file_hanlder.jar", "server config.yml"]
